# Logistic Regression on Breast Cancer Dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### Loading the dataset

In [3]:
df = pd.read_csv('dataset_final.csv')

In [4]:
df.head()

   symmetry_mean  fractal_dimension_mean  ...  symmetry_worst  diagnosis_encoded
0         0.2419                 0.07871  ...          0.4601                  1
1         0.1812                 0.05667  ...          0.2750                  1
2         0.2069                 0.05999  ...          0.3613                  1
3         0.2597                 0.09744  ...          0.6638                  1
4         0.1809                 0.05883  ...          0.2364                  1

[5 rows x 13 columns]

In [5]:
df.tail()

     symmetry_mean  fractal_dimension_mean  ...  symmetry_worst  diagnosis_encoded
564         0.1726                 0.05623  ...          0.2060                  1
565         0.1752                 0.05533  ...          0.2572                  1
566         0.1590                 0.05648  ...          0.2218                  1
567         0.2397                 0.07016  ...          0.4087                  1
568         0.1587                 0.05884  ...          0.2871                  0

[5 rows x 13 columns]

In [6]:
df['diagnosis_encoded'].value_counts()

diagnosis_encoded
0    357
1    212
Name: count, dtype: int64

In [7]:
y=df['diagnosis_encoded']
x=df.drop('diagnosis_encoded',axis=1)

In [8]:
x

     symmetry_mean  ...  symmetry_worst
0           0.2419  ...          0.4601
1           0.1812  ...          0.2750
2           0.2069  ...          0.3613
3           0.2597  ...          0.6638
4           0.1809  ...          0.2364
..             ...  ...             ...
564         0.1726  ...          0.2060
565         0.1752  ...          0.2572
566         0.1590  ...          0.2218
567         0.2397  ...          0.4087
568         0.1587  ...          0.2871

[569 rows x 12 columns]

In [9]:
y

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis_encoded, Length: 569, dtype: int64

### Train Test Split

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state = 42)

print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(426, 12) (143, 12) (426,) (143,)

## Logistic Regression

In [11]:
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import accuracy_score,f1_score

In [12]:
model=LogisticRegressionCV(cv=10,random_state=42,max_iter=100)

In [13]:
model.fit(x_train,y_train)

d:\Codes\Breast_Cancer_Detector_logistic_Regression\env\Lib\site-packages\sklearn\linear_model\_logistic.py:1780: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
d:\Codes\Breast_Cancer_Detector_logistic_Regression\env\Lib\site-packages\sklearn\linear_model\_logistic.py:1823: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(
d:\Codes\Breast_Cancer_Detector_logistic_Regression\env\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Codes\Breast_Cancer_Detector_logistic_Regression\env\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Codes\Breast_Cancer_Detector_logistic_Regression\env\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Codes\Breast_Cancer_Detector_logistic_Regression\env\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegressionCV(cv=10, random_state=42)

In [14]:
y_pred=model.predict(x_test)
y_pred

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [15]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)
f1=f1_score(y_test,y_pred)
print(f1)

0.951048951048951
0.9369369369369369

In [16]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_pred)
print(r2)

0.791718684977112

In [17]:
from sklearn.svm import LinearSVC

In [18]:
svc = LinearSVC()
svc.fit(x_train,y_train)

LinearSVC()

In [19]:
y_pred_svc = svc.predict(x_test)

In [20]:
r2_score(y_test,y_pred_svc)

0.8512276321265085

In [21]:
accuracy_score(y_test,y_pred_svc)

0.965034965034965

## Pickling the model

In [25]:
import pickle
pickle.dump(svc,open('svc.pkl','wb'))